// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.sonatype.timeline.proto;

public final class TimeLineRecordProtos {
  private TimeLineRecordProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class TimeLineRecord extends
      com.google.protobuf.GeneratedMessage {
    // Use TimeLineRecord.newBuilder() to construct.
    private TimeLineRecord() {}
    
    private static final TimeLineRecord defaultInstance = new TimeLineRecord();
    public static TimeLineRecord getDefaultInstance() {
      return defaultInstance;
    }
    
    public TimeLineRecord getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_fieldAccessorTable;
    }
    
    public static final class Data extends
        com.google.protobuf.GeneratedMessage {
      // Use Data.newBuilder() to construct.
      private Data() {}
      
      private static final Data defaultInstance = new Data();
      public static Data getDefaultInstance() {
        return defaultInstance;
      }
      
      public Data getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_Data_descriptor;
      }
      
      @Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.internal_static_timeline_TimeLineRecord_Data_fieldAccessorTable;
      }
      
      // required string key = 1;
      private boolean hasKey;
      private java.lang.String key_ = "";
      public boolean hasKey() { return hasKey; }
      public java.lang.String getKey() { return key_; }
      
      // optional string value = 2;
      private boolean hasValue;
      private java.lang.String value_ = "";
      public boolean hasValue() { return hasValue; }
      public java.lang.String getValue() { return value_; }
      
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return new Builder(); }
      public static Builder newBuilder(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data prototype) {
        return new Builder().mergeFrom(prototype);
      }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        // Construct using org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.newBuilder()
        private Builder() {}
        
        org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data result = new org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data();
        
        @Override
        protected org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data internalGetResult() {
          return result;
        }
        
        @Override
        public Builder clear() {
          result = new org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data();
          return this;
        }
        
        @Override
        public Builder clone() {
          return new Builder().mergeFrom(result);
        }
        
        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.getDescriptor();
        }
        
        public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getDefaultInstanceForType() {
          return org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.getDefaultInstance();
        }
        
        public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data build() {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result);
          }
          return buildPartial();
        }
        
        private org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data buildPartial() {
          org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data returnMe = result;
          result = null;
          return returnMe;
        }
        
        
        // required string key = 1;
        public boolean hasKey() {
          return result.hasKey();
        }
        public java.lang.String getKey() {
          return result.getKey();
        }
        public Builder setKey(java.lang.String value) {
          result.hasKey = true;
          result.key_ = value;
          return this;
        }
        public Builder clearKey() {
          result.hasKey = false;
          result.key_ = "";
          return this;
        }
        
        // optional string value = 2;
        public boolean hasValue() {
          return result.hasValue();
        }
        public java.lang.String getValue() {
          return result.getValue();
        }
        public Builder setValue(java.lang.String value) {
          result.hasValue = true;
          result.value_ = value;
          return this;
        }
        public Builder clearValue() {
          result.hasValue = false;
          result.value_ = "";
          return this;
        }
      }
      
      static {
        org.sonatype.timeline.proto.TimeLineRecordProtos.getDescriptor();
      }
    }
    
    // optional int64 timestamp = 1;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // optional string type = 2;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    // optional string subType = 3;
    private boolean hasSubType;
    private java.lang.String subType_ = "";
    public boolean hasSubType() { return hasSubType; }
    public java.lang.String getSubType() { return subType_; }
    
    // repeated .timeline.TimeLineRecord.Data data = 4;
    private java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> data_ =
      java.util.Collections.emptyList();
    public java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> getDataList() {
      return data_;
    }
    public int getDataCount() { return data_.size(); }
    public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getData(int index) {
      return data_.get(index);
    }
    
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.newBuilder()
      private Builder() {}
      
      org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord result = new org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord();
      
      @Override
      protected org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.getDescriptor();
      }
      
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord getDefaultInstanceForType() {
        return org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.getDefaultInstance();
      }
      
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord buildPartial() {
        if (result.data_ != java.util.Collections.EMPTY_LIST) {
          result.data_ =
            java.util.Collections.unmodifiableList(result.data_);
        }
        org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional int64 timestamp = 1;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // optional string type = 2;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = "";
        return this;
      }
      
      // optional string subType = 3;
      public boolean hasSubType() {
        return result.hasSubType();
      }
      public java.lang.String getSubType() {
        return result.getSubType();
      }
      public Builder setSubType(java.lang.String value) {
        result.hasSubType = true;
        result.subType_ = value;
        return this;
      }
      public Builder clearSubType() {
        result.hasSubType = false;
        result.subType_ = "";
        return this;
      }
      
      // repeated .timeline.TimeLineRecord.Data data = 4;
      public java.util.List<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> getDataList() {
        return java.util.Collections.unmodifiableList(result.data_);
      }
      public int getDataCount() {
        return result.getDataCount();
      }
      public org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data getData(int index) {
        return result.getData(index);
      }
      public Builder setData(int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data value) {
        result.data_.set(index, value);
        return this;
      }
      public Builder setData(int index, org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder builderForValue) {
        result.data_.set(index, builderForValue.build());
        return this;
      }
      public Builder addData(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data value) {
        if (result.data_.isEmpty()) {
          result.data_ = new java.util.ArrayList<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data>();
        }
        result.data_.add(value);
        return this;
      }
      public Builder addData(org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder builderForValue) {
        if (result.data_.isEmpty()) {
          result.data_ = new java.util.ArrayList<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data>();
        }
        result.data_.add(builderForValue.build());
        return this;
      }
      public Builder addAllData(
          java.lang.Iterable<? extends org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data> values) {
        if (result.data_.isEmpty()) {
          result.data_ = new java.util.ArrayList<org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data>();
        }
        super.addAll(values, result.data_);
        return this;
      }
      public Builder clearData() {
        result.data_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      org.sonatype.timeline.proto.TimeLineRecordProtos.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_timeline_TimeLineRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_timeline_TimeLineRecord_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_timeline_TimeLineRecord_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_timeline_TimeLineRecord_Data_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\024timelinerecord.proto\022\010timeline\"\223\001\n\016Tim" +
      "eLineRecord\022\021\n\ttimestamp\030\001 \001(\003\022\014\n\004type\030\002" +
      " \001(\t\022\017\n\007subType\030\003 \001(\t\022+\n\004data\030\004 \003(\0132\035.ti" +
      "meline.TimeLineRecord.Data\032\"\n\004Data\022\013\n\003ke" +
      "y\030\001 \002(\t\022\r\n\005value\030\002 \001(\tB3\n\033org.sonatype.t" +
      "imeline.protoB\024TimeLineRecordProtos";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_timeline_TimeLineRecord_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_timeline_TimeLineRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_timeline_TimeLineRecord_descriptor,
              new java.lang.String[] { "Timestamp", "Type", "SubType", "Data", },
              org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.class,
              org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Builder.class);
          internal_static_timeline_TimeLineRecord_Data_descriptor =
            internal_static_timeline_TimeLineRecord_descriptor.getNestedTypes().get(0);
          internal_static_timeline_TimeLineRecord_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_timeline_TimeLineRecord_Data_descriptor,
              new java.lang.String[] { "Key", "Value", },
              org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.class,
              org.sonatype.timeline.proto.TimeLineRecordProtos.TimeLineRecord.Data.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
